# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Diodos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import os
# --- Intentar importar RPi.GPIO ---
try:
    import RPi.GPIO as GPIO
    RPI_AVAILABLE = True
except ImportError:
    print("⚠️ Ejecutando en PC (GPIO no disponible).")
    RPI_AVAILABLE = False


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 693)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(27, 27, 27);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # --- Título ---
        self.TITULO = QtWidgets.QLabel(self.centralwidget)
        self.TITULO.setGeometry(QtCore.QRect(210, 10, 471, 141))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.TITULO.setFont(font)
        self.TITULO.setAlignment(QtCore.Qt.AlignCenter)
        self.TITULO.setObjectName("TITULO")

        # --- Créditos ---
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 460, 390, 133))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)

        self.Nombres = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Nombres.setFont(QtGui.QFont("Arial", 12, QtGui.QFont.Bold))
        self.Nombres.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.Nombres)

        self.subtitulo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.subtitulo.setFont(QtGui.QFont("Arial", 11, QtGui.QFont.Bold))
        self.subtitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.subtitulo)

        self.year = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.year.setFont(QtGui.QFont("Arial", 11, QtGui.QFont.Bold))
        self.year.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.year)

        # --- Logo ---
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(470, 460, 331, 131))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)

        # --- Botones LED1 y LED2 ---
        self.push_led1 = QtWidgets.QPushButton(self.centralwidget)
        self.push_led1.setGeometry(QtCore.QRect(200, 220, 191, 71))
        self.push_led1.setFont(QtGui.QFont("Lucida Console", 16))
        self.push_led1.setStyleSheet("background-color:rgb(0, 170, 0)")
        self.push_led1.setObjectName("push_led1")

        self.push_led2 = QtWidgets.QPushButton(self.centralwidget)
        self.push_led2.setGeometry(QtCore.QRect(500, 220, 191, 71))
        self.push_led2.setFont(QtGui.QFont("Lucida Console", 16))
        self.push_led2.setStyleSheet("background-color:rgb(0, 0, 255)")
        self.push_led2.setObjectName("push_led2")

        # --- Sliders LED3 y LED4 ---
        self.slider_led3 = QtWidgets.QSlider(self.centralwidget)
        self.slider_led3.setGeometry(QtCore.QRect(210, 380, 160, 22))
        self.slider_led3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_led3.setObjectName("slider_led3")

        self.slider_led4 = QtWidgets.QSlider(self.centralwidget)
        self.slider_led4.setGeometry(QtCore.QRect(520, 380, 160, 22))
        self.slider_led4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_led4.setObjectName("slider_led4")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 320, 101, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 320, 101, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        MainWindow.setCentralWidget(self.centralwidget)

        # --- Menú ---
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # --- Inicializar GPIO ---
        self.init_gpio()

        # --- Eventos ---
        self.push_led1.clicked.connect(self.toggle_led1)
        self.push_led2.clicked.connect(self.toggle_led2)
        self.slider_led3.valueChanged.connect(self.set_led3_brightness)
        self.slider_led4.valueChanged.connect(self.set_led4_brightness)

        # Estado inicial LEDs
        self.led1_state = False
        self.led2_state = False
        self.mostrar_logo("Logoecci.png")

    def mostrar_logo(self, nombre_archivo):
        """Muestra el logo en el QLabel inferior derecho"""
        ruta = os.path.join(os.path.dirname(__file__), nombre_archivo)

        if os.path.exists(ruta):
            pixmap = QtGui.QPixmap(ruta)
            pixmap = pixmap.scaled(self.logo.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
            self.logo.setPixmap(pixmap)
        else:
            self.logo.setText("Logo no encontrado")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Control de LEDs"))
        self.TITULO.setText(_translate("MainWindow", "<html><body><p><span style=\" font-size:28pt; color:#ffffff;\">DIODOS</span></p></body></html>"))
        self.Nombres.setText(_translate("MainWindow", "<html><body><p><span style=\" color:#ffffff;\">Cristian Zamora - Laura Siabato</span></p></body></html>"))
        self.subtitulo.setText(_translate("MainWindow", "<html><body><p><span style=\" color:#ffffff;\">Ing. Mecatrónica Electiva Robótica</span></p></body></html>"))
        self.year.setText(_translate("MainWindow", "<html><body><p><span style=\" color:#ffffff;\">2025 - 1</span></p></body></html>"))
        self.push_led1.setText(_translate("MainWindow", "LED 1"))
        self.push_led2.setText(_translate("MainWindow", "LED 2"))
        self.label_2.setText(_translate("MainWindow", "<html><body><p><span style=\" font-size:22pt; color:#ffffff;\">LED 3</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><body><p><span style=\" font-size:22pt; color:#ffffff;\">LED 4</span></p></body></html>"))

    # ------------------ GPIO ------------------
    def init_gpio(self):
        if not RPI_AVAILABLE:
            return
        GPIO.setmode(GPIO.BCM)
        GPIO.setwarnings(False)

        # Pines
        self.PIN_LED1 = 5
        self.PIN_LED2 = 6
        self.PIN_LED3 = 13
        self.PIN_LED4 = 19

        GPIO.setup(self.PIN_LED1, GPIO.OUT)
        GPIO.setup(self.PIN_LED2, GPIO.OUT)
        GPIO.setup(self.PIN_LED3, GPIO.OUT)
        GPIO.setup(self.PIN_LED4, GPIO.OUT)

        # PWM para LED3 y LED4
        self.pwm_led3 = GPIO.PWM(self.PIN_LED3, 1000)  # 1kHz
        self.pwm_led4 = GPIO.PWM(self.PIN_LED4, 1000)
        self.pwm_led3.start(0)
        self.pwm_led4.start(0)

    def toggle_led1(self):
        if not RPI_AVAILABLE:
            print("LED1 toggle (simulado)")
            self.push_led1.setStyleSheet("Background-color:green;color:white;")
            return
        self.led1_state = not self.led1_state
        GPIO.output(self.PIN_LED1, self.led1_state)

    def toggle_led2(self):
        if not RPI_AVAILABLE:
            print("LED2 toggle (simulado)")
            self.push_led2.setStyleSheet("Background-color:blue;color:white;")
            return
        self.led2_state = not self.led2_state
        GPIO.output(self.PIN_LED2, self.led2_state)

    def set_led3_brightness(self, value):
        if not RPI_AVAILABLE:
            print(f"LED3 PWM (simulado): {value}%")
            intensidad = int(255 * value / 100)  # 0-255
            self.slider_led3.setStyleSheet(f"background-color: rgb({intensidad},{intensidad},{intensidad}); color: black;")
            return
        self.pwm_led3.ChangeDutyCycle(value)
        intensidad = int(255 * value / 100)  # 0-255
        self.slider_led3.setStyleSheet(f"background-color: rgb({intensidad},{intensidad},{intensidad}); color: black;")

    def set_led4_brightness(self, value):
        if not RPI_AVAILABLE:
            print(f"LED4 PWM (simulado): {value}%")
            intensidad = int(255 * value / 100)  # 0-255
            self.slider_led4.setStyleSheet(f"background-color: rgb({intensidad},{intensidad},{intensidad}); color: black;")
            return
        self.pwm_led4.ChangeDutyCycle(value)
        intensidad = int(255 * value / 100)  # 0-255
        self.slider_led4.setStyleSheet(f"background-color: rgb({intensidad},{intensidad},{intensidad}); color: black;")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    try:
        sys.exit(app.exec_())
    finally:
        if RPI_AVAILABLE:
            GPIO.cleanup()
